---
title: "Content Classes"
description: |
  Use css to create content classes to style elements
author:
  - name: Emil Hvitfeldt
    url: {}
date: 05-20-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - css
  - content classes
preview: preview.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Custom content classes are a great way to quick style elements of your slides. Create a css class, here is a class called `.orange` which sets the color to orange.

```{css}
.orange {
  color: orange;
}
```

If you write `.orange[some text]` then it will be rendered as <span style="color: orange;">some text</span> in the final document.

# Result

```{r, echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "../../static/examples/content-classes/index.html", 
  ratio = "4:3"
)
```

# Rmd

```{r, echo=FALSE, class.output = "rmd"}
cat(readr::read_lines("../../static/examples/content-classes/index.Rmd"), sep = "\n")
```

# stylesheet.css

```{r, echo=FALSE, class.output = "cssfile"}
cat(readr::read_lines("../../static/examples/content-classes/stylesheet.css"), sep = "\n")
```
