---
title: "fancy first letter"
description: |
  Big first letters
author:
  - name: Emil Hvitfeldt
    url: {}
date: 05-09-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - css
preview: preview.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Drop caps](https://www.smashingmagazine.com/2012/04/drop-caps-historical-use-and-current-best-practices/) are a fun way to add a little bit of flair to a paragraph.

Using the `::first-letter` pseudo-element we can specifying the style of that is applied to the first letter of a paragraph.

You can go above and beyond and specify a custom font to be used in the drop-cap. The [romantik](https://www.1001fonts.com/romantik-font.html) font was used in this example.

All files found [here](https://github.com/EmilHvitfeldt/xaringan-gallery/tree/master/fancy-first-letter).

# Result

```{r, echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "../../static/examples/fancy-first-letter/index.html", 
  ratio = "4:3"
)
```

# Rmd

```{r, echo=FALSE, class.output = "rmd"}
cat(readr::read_lines("../../static/examples/fancy-first-letter/index.Rmd"), sep = "\n")
```

# stylesheet.css

```{r, echo=FALSE, class.output = "css"}
cat(readr::read_lines("../../static/examples/fancy-first-letter/stylesheet.css"), sep = "\n")
```
